### ISSUE TITLE
Denjin makai II

### ISSUE THREAD

**Issue by cecilmax** [arcadez/mame2003-plus-libretro#31]
Hello,

I try to load guardians (denjin makai ii) it just return to retroarch after a second, no screen or anything. I know it work on wii because I can load it with FBA core.. and I make sure I have the good rom to load ;)

EDIT: Denjin Makai I doesnt load too, same problem as Denjin Makai II ..

**Comment by arcadez** [comment]
There are literally 100's of games that dont work with this core but do so when using the MAME78 
on a PC, take Denjin Makai for example that's one of my additions to this core it works perfectly in 
my testing core and since the code i then ported across to this core is line for line the exact same 
then in theory it should work here also as for why it doesn't i dunno TBH.

**Comment by cecilmax** [comment]
Can you share which rom you use ? I will test it :)

**Comment by arcadez** [comment]
goto doperoms and grab it from there

**Comment by cecilmax** [comment]
Still have the same bug with the rom from doperoms. The game just doesnt load at all.. Why guardians doesnt load with mame 2003 plus and it does with FBA ?
